[package]
name = "native_spark"
version = "0.1.0"
authors = ["raja <rajasekar3eg@gmail.com>"]
edition = "2018"

build = "build.rs"

[lib]
name = "native_spark"

[dependencies]
objekt = "0.1.2"
downcast-rs = "1.0.3"
threadpool = "1.7.1"
#derivative = "1.0.2"
serde_traitobject = "0.2"
toml = "0.5.0"
serde_closure = "0.2"
serde = { version = "1.0.90", features = ["rc"] }
reqwest = "0.9.16"
lazy_static = "1.3.0"
serde_derive = "1.0.90"
fasthash = "0.4.0"
bincode = "1.1.3"
num_cpus = "1.10.1"
uuid = { version = "0.8", features = ["v4"] }
env_logger = "0.5"
actix-web = "1.0.0-beta.3"
#actix-files = "0.1.0-beta.1"
rand = "0.7"
rand_pcg = "0.2"
rand_distr = "0.2"
parking_lot = { version = "0.9.0", features = ["serde"] }
capnp = "0.9.5"
simplelog = "0.7.4"
log = "0.4.8"
thiserror = "1.0"

[build-dependencies]
capnpc = "0.9.5"

[dev-dependencies]
chrono = "0.4"
itertools = "0.8.0"
parquet = "0.15.0"
tempfile = "3"
