version: '3'

networks:
  native-spark:

services:
  ns_master:
    image: native_spark:latest
    ports:
      - "3000"
    tty: true
    networks:
      native-spark:

  ns_worker:
    image: native_spark:latest
    ports:
      - "10500"
      - "22"
    tty: true
    networks:
      native-spark:
